apiVersion: v1
kind: Service
metadata:
  name: rag-gradio
spec:
  type: NodePort
  selector:
    app: rag-gradio
  ports:
    - name: http
      port: 7860
      targetPort: 7860
      nodePort: 32080

