# k8s/ingress-nginx.yaml
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: ingress-nginx
#  namespace: ingress-nginx
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: ingress-nginx-controller
#  namespace: ingress-nginx
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app.kubernetes.io/name: ingress-nginx
#      app.kubernetes.io/component: controller
#  template:
#    metadata:
#      labels:
#        app.kubernetes.io/name: ingress-nginx
#        app.kubernetes.io/component: controller
#    spec:
#      hostNetwork: false
#      serviceAccountName: ingress-nginx
#      containers:
#        - name: controller
#          image: registry.k8s.io/ingress-nginx/controller:v1.14.1
#          args:
#            - /nginx-ingress-controller
#            - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
#          env:
#            - name: POD_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#            - name: POD_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
#          ports:
#            - containerPort: 80
#            - containerPort: 443
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: ingress-nginx-controller
#  namespace: ingress-nginx
#spec:
#  type: NodePort  # <-- NodePort makes it accessible outside WSL2
#  selector:
#    app.kubernetes.io/name: ingress-nginx
#    app.kubernetes.io/component: controller
#  ports:
#    - name: http
#      port: 80
#      nodePort: 32080
#    - name: https
#      port: 443
#      nodePort: 32443
#
#