apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-pv
spec:
  capacity:
    storage: 50Gi   # increase to 50Gi or more
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/migue/rag/models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi   # match PV
  volumeName: models-pv
  storageClassName: ""
---
# Vector DB volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vector-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/migue/rag/vector_db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-vector-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: vector-db-pv
  storageClassName: ""
---
# Documents volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: documents-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/migue/rag/documents
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-documents-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: documents-pv
  storageClassName: ""
