mlflow_uri: "http://localhost:32081"

evaluator_model:
  label: "rag_evaluator"
  hf_id: "roberta-large-mnli"
  local_path: "/models/evaluator"
  type: "evaluator"

reranker_model:
  label: "reranker_model"
  hf_id: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  local_path: "/models/reranker"
  type: "cross-encoder"

embedding_model:
  label: "vector_embedding"
  hf_id: "sentence-transformers/all-MiniLM-L6-v2"
  local_path: "/models/embeddings"
  type: "embedding"

# CAUSAL GENERATION MODEL
generation_model:
  label: "causal_gen"
  hf_id: "distilgpt2"  # or any causal LM you want
  local_path: "/models/generation"
  type: "causal"

thresholds:
  retrieval_hit_rate@5: 0.60
  retrieval_recall@5: 0.40
  reranker_gain: 0.10
  context_precision@3: 0.50
  avg_eval_score: 0.50
  min_eval_score: 0.20
  answer_groundedness: 0.30
  avg_latency_ms: 3000